# Generated by Django 2.2.6 on 2019-11-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Enter field documentation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Enter field documentation',
            new_name='name',
        ),
    ]
