# Generated by Django 2.2.6 on 2019-11-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191102_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Electric',
        ),
    ]
